<template>
  <div>
    <h1>Search</h1>
    <div>
      Locations
      <select v-model="selectedValue.selectedState">
        <option v-for="state in states" :key="state.key" :value="state">
          {{ state }}
        </option>
      </select>
      <select v-model="selectedValue.selectedCity">
        <option v-for="city in cities" :key="city.key" :value="city">
          {{ city }}
        </option>
      </select>
      <select v-model="selectedValue.selectedHighway">
        <option
          v-for="highway in highways"
          :key="highway.key"
          :value="highway"
          >{{ highway }}</option
        >
      </select>
    </div>
    <div>
      Type
      <label v-for="type in types" :key="type.key">
        {{ type }}
        <input
          type="checkbox"
          v-model="selectedValue.selectedTypes"
          :value="type"
        />
      </label>
      <button @click="$emit('submitSelectedValue', selectedValue)">
        search
      </button>
    </div>
    <!-- <div>
      Amenities
      <label v-for="amenity in amenities" :key="amenity.key">
        {{ amenity }}
        <input
          type="checkbox"
          :value="amenity"
          v-model="selectedValue.selectedAmenities"
          @change="$emit('submitSelectedValue', selectedValue)"
        />
      </label>
    </div> -->
    <!-- <div>
      Restaurants
      <label v-for="restaraunt in restaurants" :key="restaraunt.key">
        {{ restaraunt }}
        <input
          type="checkbox"
          :value="restaraunt"
          v-model="selectedValue.selectedRestaurants"
          @change="$emit('submitSelectedValue', selectedValue)"
        />
      </label>
    </div> -->
  </div>
</template>

<script>
export default {
  name: "FilterRegion",
  data() {
    return {
      types: ["Travel Stop", "Country Store"],
      // amenities: ["ATM", "Wifi", "other"],
      // restaurants: ["Arby's", "Wendy's", "other"],
      selectedValue: {
        selectedTypes: [],
        selectedHighway: "ALL",
        selectedCity: "ALL",
        selectedState: "ALL",
        // selectedAmenities: [],
        // selectedRestaurants: [],
      },
      states: [
        "ALL",
        "AL",
        "AR",
        "AZ",
        "CA",
        "CO",
        "FL",
        "GA",
        "IA",
        "ID",
        "IL",
        "IN",
        "KS",
        "KY",
        "LA",
        "MD",
        "MI",
        "MN",
        "MO",
        "MS",
        "MT",
        "NC",
        "ND",
        "NE",
        "NJ",
        "NM",
        "NV",
        "NY",
        "OH",
        "OK",
        "OR",
        "PA",
        "SC",
        "SD",
        "TN",
        "TX",
        "UT",
        "VA",
        "WA",
        "WI",
        "WV",
        "WY",
      ],
      cities: [
        "ALL",
        "Ada",
        "Albert Lea",
        "Albuquerque",
        "Altus",
        "Alva",
        "Amarillo",
        "Andrews",
        "Angleton",
        "Angola",
        "Anna",
        "Anthony",
        "Ardmore",
        "Arkansas City",
        "Atoka",
        "Auburndale",
        "Aurora ",
        "Baird",
        "Barstow",
        "Batesville",
        "Baxter ",
        "Baytown",
        "Beaver",
        "Belleville",
        "Bennett",
        "Benson",
        "Bevier",
        "Bidwell",
        "Biloxi",
        "Binghamton",
        "Blacksburg",
        "Bloomsdale",
        "Blytheville",
        "Boardman",
        "Boise City",
        "Boonville",
        "Bordentown",
        "Box Elder",
        "Bridgeton",
        "Brigham City",
        "Broken Bow",
        "Brunswick",
        "Buckeye",
        "Buena Vista",
        "Buffalo",
        "Burbank",
        "Burlington",
        "Calvert City ",
        "Canaan",
        "Canton",
        "Carlisle",
        "Casa Grande",
        "Cayce",
        "Cedar City ",
        "Chandler ",
        "Chanute",
        "Charleston",
        "Cheyenne",
        "Chickasha",
        "Choctaw",
        "Chouteau",
        "Christiana",
        "Circleville",
        "Clanton",
        "Claude",
        "Clayton",
        "Cleveland ",
        "Clinton",
        "Clive",
        "Clovis",
        "Coachella",
        "Colbert ",
        "Colby",
        "Columbia",
        "Columbus",
        "Comanche",
        "Comfort",
        "Conneaut",
        "Corbin",
        "Corning",
        "Cottondale",
        "Crescent",
        "Cumberland",
        "Cunningham",
        "Dallas",
        "Dandridge",
        "Davenport",
        "Dayton",
        "Deer Park",
        "Dekorra - Poynette",
        "Demotte",
        "Denton",
        "Dickson",
        "Dillon",
        "Dodge City",
        "Domino",
        "Dublin ",
        "Dumas",
        "Duncan",
        "Dunn",
        "Durant",
        "Duson",
        "Dwight",
        "Dyersburg",
        "Eads",
        "Eagleville",
        "Edinburg",
        "Edna",
        "El Paso",
        "El Reno",
        "Elk City",
        "Ellensburg",
        "Ellis",
        "Ellsworth",
        "Ely",
        "Emerson",
        "Encinal",
        "Enid",
        "Erick",
        "Eufaula",
        "Evergreen",
        "Fair Play",
        "Fairfield",
        "Fairview",
        "Falkville",
        "Fargo",
        "Fernley",
        "Flowood",
        "Floyd",
        "Fond du Lac",
        "Fort Mill",
        "Fort Pierce",
        "Fort Stockton",
        "Fort Worth",
        "Fountain",
        "Franklin",
        "Gallup",
        "Garden City",
        "Gary",
        "Gila Bend",
        "Grand Junction",
        "Grayson",
        "Great Bend",
        "Greenup",
        "Greenville",
        "Greenwood",
        "Gulfport",
        "Gunnison",
        "Guthrie",
        "Guymon",
        "Hagerstown",
        "Hamburg",
        "Hamel",
        "Hardin",
        "Harrisonville",
        "Haubstadt",
        "Hawthorne",
        "Hays",
        "Hearne",
        "Hennessey",
        "Henryetta",
        "Hereford",
        "Heyburn ",
        "Hillsboro",
        "Hinton ",
        "Hogansville",
        "Holcomb",
        "Hollis",
        "Hooker",
        "Horse Cave",
        "Houston",
        "Hubbard",
        "Hudson",
        "Hungerford",
        "Hutchins",
        "Idaho Falls",
        "Ina",
        "Indianola",
        "Italy",
        "Jackson",
        "Jacksonville",
        "Jasper",
        "Jeffersonville ",
        "Jonesboro",
        "Jonestown ",
        "Joplin",
        "Joseph City",
        "Kankakee",
        "Katy",
        "Kingfisher",
        "Kingman",
        "Kingsville ",
        "Knightstown",
        "Knoxville",
        "La Junta",
        "Lake Charles",
        "Lake Havasu City",
        "Lake",
        "Lamar",
        "Lambsburg",
        "Las Cruces",
        "Las Vegas ",
        "Lawton",
        "Le Roy ",
        "Leary",
        "Lee ",
        "Lenoir City",
        "Lexington",
        "Liberal",
        "Lindsay",
        "Little Rock",
        "Lodi",
        "Londonderry",
        "Lordsburg",
        "Lost Hills ",
        "Loxley",
        "Lubbock",
        "Lufkin",
        "Luling",
        "Macon",
        "Madill",
        "Magee",
        "Mangum",
        "Marion",
        "Marlow",
        "Marshall ",
        "Matthews   ",
        "Max Meadows",
        "McCalla",
        "McComb",
        "McLoud",
        "McPherson",
        "Meade",
        "Meadowview",
        "Memphis ",
        "Memphis",
        "Menomonie",
        "Miami",
        "Midland",
        "Midlothian",
        "Mifflinville ",
        "Milan",
        "Minden ",
        "Monte Vista",
        "Moody",
        "Moore Haven",
        "Morrilton",
        "Mossy Head",
        "Mount Vernon",
        "Muscle Shoals",
        "Napavine",
        "Nashville",
        "Natalia",
        "Neosho",
        "New Baden",
        "New London",
        "Newberry",
        "Newton ",
        "Nickajack Lake",
        "Norfolk",
        "Norman",
        "North Baltimore",
        "North Fort Myers",
        "North Little Rock",
        "North Platte",
        "Norton",
        "Nowata",
        "Oak Creek",
        "Oakdale",
        "Ocala",
        "Odessa ",
        "Oglesby",
        "Okemah",
        "Oklahoma City",
        "Okmulgee",
        "Ontario",
        "Orangeburg ",
        "Ormond Beach ",
        "Ottawa",
        "Ozark",
        "Palestine",
        "Paris",
        "Pauls Valley",
        "Pecos",
        "Pendleton",
        "Perrysburg",
        "Phillipsburg",
        "Pittsboro",
        "Plymouth",
        "Poplarville",
        "Port Allen",
        "Port Barre",
        "Post Falls",
        "Pratt",
        "Prescott",
        "Prichard",
        "Prosser",
        "Pueblo",
        "Purcell",
        "Quanah",
        "Quartzsite",
        "Ranger",
        "Rhome",
        "Richmond ",
        "Richmond Hill ",
        "Richmond",
        "Ripley",
        "Ripon ",
        "Ritzville",
        "Rockwall",
        "Rolla ",
        "Roscoe",
        "Roseburg",
        "Ruther Glen",
        "Sadieville",
        "Saint Joseph",
        "Saint Louis",
        "Saint Paul ",
        "Salina",
        "Salisbury",
        "Salt Lake City",
        "San Antonio",
        "Santa Nella",
        "Santa Rosa",
        "Scott City",
        "Searcy",
        "Seguin",
        "Seminole",
        "Shawnee",
        "Sheboygan",
        "Shelby",
        "Shepherdsville",
        "Shorter",
        "Sidney",
        "Sikeston",
        "Sinton",
        "Sioux City",
        "Sioux Falls",
        "Skippers",
        "South Hill",
        "South Holland",
        "South Hutchinson",
        "South Jacksonville",
        "Sparta",
        "Springfield",
        "Springville",
        "Steele",
        "Strafford",
        "Sweetwater",
        "Syracuse",
        "Tacoma",
        "Tahlequah",
        "Tallulah",
        "Tecumseh",
        "Tehachapi",
        "Terre Haute",
        "Texhoma",
        "Thomson",
        "Three Rivers",
        "Tifton",
        "Tolleson",
        "Tom's Brook",
        "Tonkawa ",
        "Toomsuba ",
        "Troutdale",
        "Tucumcari",
        "Tulare",
        "Tupelo",
        "Union City",
        "Upper Sandusky",
        "Utica ",
        "Valley",
        "Valliant",
        "Van Horn",
        "Van",
        "Vinton",
        "Waco ",
        "Waddy ",
        "Wamsutter",
        "Watonga",
        "Weatherford",
        "Webbers Falls",
        "Weimar",
        "Wells ",
        "West Memphis",
        "West Point",
        "West Siloam Springs",
        "White House",
        "Whiteland",
        "Whitestown",
        "Wichita Falls",
        "Williams",
        "Williamsville",
        "Willis",
        "Williston",
        "Woodburn",
        "Woodward",
        "Yukon",
        "Yuma",
        "Zanesville",
      ],
      highways: [
        "ALL",
        "Hwy 169",
        "Hwy 18",
        "Hwy 19/76",
        "Hwy 190",
        "Hwy 2",
        "Hwy 225",
        "Hwy 23",
        "HWY 231",
        "Hwy 24",
        "Hwy 27",
        "Hwy 271",
        "Hwy 275",
        "Hwy 281",
        "Hwy 283",
        "Hwy 287",
        "HWY 287",
        "Hwy 287/50",
        "Hwy 288",
        "Hwy 30",
        "Hwy 30/23",
        "Hwy 301",
        "Hwy 35",
        "Hwy 36",
        "Hwy 370",
        "Hwy 385",
        "Hwy 400",
        "Hwy 41",
        "Hwy 412",
        "Hwy 45A",
        "Hwy 49",
        "Hwy 50",
        "HWY 50",
        "Hwy 50/93",
        "Hwy 54",
        "Hwy 58",
        "Hwy 59",
        "Hwy 59/69/Loop 287",
        "Hwy 6",
        "Hwy 60",
        "Hwy 61",
        "Hwy 63",
        "HWY 67",
        "Hwy 67",
        "Hwy 69",
        "Hwy 70",
        "Hwy 72A",
        "Hwy 74",
        "Hwy 75",
        "Hwy 77",
        "Hwy 81",
        "Hwy 82",
        "HWY 83",
        "Hwy 87",
        "Hwy 99",
        "I-10",
        "I-135",
        "I-15",
        "I-155",
        "I-16",
        "I-20",
        "I-22",
        "I-24",
        "I-240",
        "I-25",
        "I-26",
        "I-27",
        "I-280",
        "I-29",
        "I-295",
        "I-30",
        "I-35",
        "I-35E",
        "I-35W",
        "I-37",
        "I-39",
        "I-4",
        "I-40",
        "I-41",
        "I-43",
        "I-44",
        "I-45",
        "I-49",
        "I-5",
        "I-55",
        "I-57",
        "I-59",
        "I-64",
        "I-65",
        "I-68",
        "I-69",
        "I-70",
        "I-71",
        "I-72",
        "I-74",
        "I-75",
        "I-76",
        "I-77",
        "I-78",
        "I-8",
        "I-80",
        "I-81",
        "I-82",
        "I-84",
        "I-85",
        "I-90",
        "I-94",
        "I-95",
        "Loop 610",
        "null",
      ],
    };
  },
};
</script>
