<template>
  <div>
    <h1>Search</h1>
    <div>
      Locations
      <select id="state">
        <option v-for="state in states" :key="state.key" :value="state">
          {{ state }}
        </option>
      </select>
      <select id="city">
        <option v-for="city in cities" :key="city.key" :value="city">
          {{ city }}
        </option>
      </select>
      <select id="highway">
        <option
          v-for="highway in highways"
          :key="highway.key"
          :value="highway"
          >{{ highway }}</option
        >
      </select>
    </div>
    <div>
      Type
      <label v-for="type in types" :key="type.key">
        {{ type }}
        <input
          type="checkbox"
          :id="type"
          :name="type"
          :value="type"
          v-model="selectedType"
        />
      </label>
    </div>
    <div>
      Amenities
      <label v-for="amenity in amenities" :key="amenity.key">
        {{ amenity }}
        <input type="checkbox" :id="amenity" :name="amenity" :value="amenity" />
      </label>
    </div>
    <div>
      Restaraunts
      <label v-for="restaraunt in restaraunts" :key="restaraunt.key">
        {{ restaraunt }}
        <input
          type="checkbox"
          :id="restaraunt"
          :name="restaraunt"
          :value="restaraunt"
        />
      </label>
    </div>
    <button v-on: click="$emit('onSubmit')">submit</button>
  </div>
</template>

<!---
Marker Contains everything 
on Submit call filter function(selectedState,selectedCity, SelectedHiway)
filteredLcoation = marker
If(selectedState !== 'All) {
  filteredLocations = filteredLocations.filter(loc => loc.state === selectedState)
} else if (selectedCity !== "all") {
  filteredLocations = filteredLocations.filter(loc => loc.city === selectedCity)
} else if (selectedHiway !== "all") {
  filteredLocations = filteredLocations.filter(loc => loc.Hiway === selectedHiway)
}
return Filtered Locations

Then we will want to update markers
--->

<script>
export default {
  name: "FilterRegion",
  methods: {
    onSubmit() {
      console.log(this.selectedType);
    },
  },
  data() {
    return {
      states: [
        "CA",
        "OR",
        "TX",
        "ND",
        "NV",
        "OH",
        "KY",
        "NY",
        "NM",
        "MS",
        "IN",
        "WV",
        "NE",
        "MO",
        "FL",
        "AR",
        "WI",
        "NC",
        "SD",
        "OK",
        "ID",
        "GA",
        "MN",
        "PA",
        "MD",
        "WY",
        "LA",
        "MT",
        "IL",
        "TN",
        "WA",
        "NJ",
        "MI",
        "AL",
        "UT",
        "IA",
        "CO",
        "SC",
        "VA",
        "AZ",
        "KS",
      ],
      cities: [
        "Henryetta",
        "Miami",
        "Bloomsdale",
        "Troutdale",
        "Dyersburg",
        "Comfort",
        "Norfolk",
        "Jackson",
        "Scott City",
        "Erick",
        "Eagleville",
        "McCalla",
        "Falkville",
        "Horse Cave",
        "Lawton",
        "Springfield",
        "North Fort Myers",
        "Emerson",
        "Fort Worth",
        "Odessa ",
        "Duson",
        "Orangeburg ",
        "Davenport",
        "Blytheville",
        "Fair Play",
        "Tom's Brook",
        "Sikeston",
        "Marlow",
        "Katy",
        "Dublin ",
        "Tolleson",
        "Searcy",
        "New Baden",
        "Fernley",
        "Lindsay",
        "Phillipsburg",
        "Baytown",
        "Syracuse",
        "Hamel",
        "Floyd",
        "Crescent",
        "Pittsboro",
        "Post Falls",
        "Cumberland",
        "Cottondale",
        "Saint Paul ",
        "Clive",
        "Ely",
        "Liberal",
        "Richmond Hill ",
        "Perrysburg",
        "Hardin",
        "Hubbard",
        "Watonga",
        "Fort Mill",
        "Pecos",
        "Woodburn",
        "Gunnison",
        "Prichard",
        "Magee",
        "Colbert ",
        "Canaan",
        "Valley",
        "Quanah",
        "Matthews   ",
        "Woodward",
        "Williston",
        "Greenup",
        "Las Cruces",
        "Arkansas City",
        "Clanton",
        "Bidwell",
        "Benson",
        "Fond du Lac",
        "Hooker",
        "Fargo",
        "San Antonio",
        "Yuma",
        "Sidney",
        "Port Barre",
        "Richmond",
        "Terre Haute",
        "Clinton",
        "Albert Lea",
        "Andrews",
        "Chandler ",
        "Joseph City",
        "Seguin",
        "Cunningham",
        "Fairview",
        "Edinburg",
        "Gallup",
        "Boardman",
        "Moore Haven",
        "Quartzsite",
        "North Platte",
        "Corning",
        "Grayson",
        "Las Vegas ",
        "Sweetwater",
        "Heyburn ",
        "Tahlequah",
        "Hogansville",
        "Deer Park",
        "Saint Joseph",
        "Tonkawa ",
        "Shorter",
        "Aurora ",
        "Hays",
        "Steele",
        "Santa Rosa",
        "Conneaut",
        "Mount Vernon",
        "Columbia",
        "Greenwood",
        "Hutchins",
        "Lordsburg",
        "Memphis",
        "Lee ",
        "Saint Louis",
        "Skippers",
        "Franklin",
        "Natalia",
        "Dallas",
        "Chanute",
        "McComb",
        "Waddy ",
        "Max Meadows",
        "Altus",
        "Ocala",
        "Garden City",
        "Comanche",
        "North Baltimore",
        "Fort Stockton",
        "Jacksonville",
        "Neosho",
        "Hudson",
        "Webbers Falls",
        "Mossy Head",
        "Pueblo",
        "Whitestown",
        "Cayce",
        "Le Roy ",
        "Bordentown",
        "Great Bend",
        "Gila Bend",
        "Van Horn",
        "Texhoma",
        "Lost Hills ",
        "Lenoir City",
        "Circleville",
        "Gary",
        "Hereford",
        "Lodi",
        "Rockwall",
        "Santa Nella",
        "Ranger",
        "Eufaula",
        "Lake",
        "Calvert City ",
        "Blacksburg",
        "Pendleton",
        "Pratt",
        "Burbank",
        "Colby",
        "Jeffersonville ",
        "Ormond Beach ",
        "Midland",
        "Buffalo",
        "Clovis",
        "Salt Lake City",
        "Broken Bow",
        "Shelby",
        "Ardmore",
        "Joplin",
        "Williamsville",
        "Roscoe",
        "McPherson",
        "Newberry",
        "Yukon",
        "South Hill",
        "Box Elder",
        "Hinton ",
        "Lufkin",
        "Lubbock",
        "La Junta",
        "Fairfield",
        "Eads",
        "Napavine",
        "Wamsutter",
        "West Point",
        "Norton",
        "Willis",
        "Grand Junction",
        "Knightstown",
        "Ripley",
        "Hawthorne",
        "Shawnee",
        "El Reno",
        "Dayton",
        "Sadieville",
        "Canton",
        "Beaver",
        "Gulfport",
        "Toomsuba ",
        "Jonesboro",
        "Indianola",
        "Wells ",
        "Macon",
        "Hearne",
        "Ellsworth",
        "Van",
        "Whiteland",
        "Haubstadt",
        "Midlothian",
        "Zanesville",
        "Leary",
        "Nowata",
        "Vinton",
        "Knoxville",
        "Bennett",
        "Ritzville",
        "Mifflinville ",
        "Strafford",
        "Moody",
        "Richmond ",
        "Houston",
        "Pauls Valley",
        "Charleston",
        "Tallulah",
        "El Paso",
        "Elk City",
        "Brunswick",
        "Tehachapi",
        "Muscle Shoals",
        "Springville",
        "White House",
        "Monte Vista",
        "Loxley",
        "Lamar",
        "Boise City",
        "Poplarville",
        "Columbus",
        "Valliant",
        "Belleville",
        "Hagerstown",
        "Sioux Falls",
        "Weatherford",
        "Domino",
        "Guthrie",
        "Evergreen",
        "Jonestown ",
        "Purcell",
        "Three Rivers",
        "Meade",
        "Marshall ",
        "Kankakee",
        "Oglesby",
        "Milan",
        "Dunn",
        "Oakdale",
        "Morrilton",
        "Demotte",
        "Seminole",
        "Fountain",
        "Jasper",
        "Prosser",
        "Ina",
        "Buena Vista",
        "Rhome",
        "Angola",
        "Sheboygan",
        "Lake Havasu City",
        "Kingfisher",
        "Ada",
        "Batesville",
        "Carlisle",
        "Harrisonville",
        "Waco ",
        "Norman",
        "Okemah",
        "Corbin",
        "Guymon",
        "Anna",
        "Dillon",
        "Auburndale",
        "Greenville",
        "Wichita Falls",
        "Tulare",
        "Cleveland ",
        "Burlington",
        "Cheyenne",
        "McLoud",
        "Ellis",
        "South Hutchinson",
        "Idaho Falls",
        "Prescott",
        "Ruther Glen",
        "Kingman",
        "Ellensburg",
        "Paris",
        "Italy",
        "Lexington",
        "Meadowview",
        "Edna",
        "Lambsburg",
        "Salina",
        "Thomson",
        "Chickasha",
        "Fort Pierce",
        "Ottawa",
        "Anthony",
        "Enid",
        "Tecumseh",
        "Atoka",
        "Ripon ",
        "Denton",
        "Plymouth",
        "Dekorra - Poynette",
        "Utica ",
        "Claude",
        "West Memphis",
        "Baird",
        "Hillsboro",
        "Madill",
        "Memphis ",
        "Barstow",
        "Hennessey",
        "Minden ",
        "Hungerford",
        "Port Allen",
        "Tucumcari",
        "Okmulgee",
        "Boonville",
        "Buckeye",
        "Angleton",
        "Baxter ",
        "Sioux City",
        "Oak Creek",
        "Newton ",
        "Alva",
        "Upper Sandusky",
        "Hollis",
        "Coachella",
        "Flowood",
        "Menomonie",
        "Holcomb",
        "Albuquerque",
        "Dumas",
        "Amarillo",
        "Bridgeton",
        "Dwight",
        "Christiana",
        "Londonderry",
        "Clayton",
        "Encinal",
        "Mangum",
        "Binghamton",
        "Nashville",
        "Bevier",
        "Brigham City",
        "Weimar",
        "Hamburg",
        "Tupelo",
        "Marion",
        "Luling",
        "Sinton",
        "Roseburg",
        "New London",
        "Rolla ",
        "Choctaw",
        "Ontario",
        "Dodge City",
        "Tacoma",
        "Duncan",
        "South Holland",
        "Biloxi",
        "Kingsville ",
        "Lake Charles",
        "Shepherdsville",
        "Dickson",
        "Tifton",
        "Williams",
        "Cedar City ",
        "South Jacksonville",
        "North Little Rock",
        "Ozark",
        "Chouteau",
        "Oklahoma City",
        "Union City",
        "West Siloam Springs",
        "Durant",
        "Sparta",
        "Casa Grande",
        "Dandridge",
        "Palestine",
        "Salisbury",
        "Little Rock",
        "Nickajack Lake",
      ],
      highways: [
        "Hwy 30/23",
        "null",
        "I-44",
        "HWY 67",
        "Hwy 82",
        "I-22",
        "I-27",
        "Hwy 19/76",
        "I-59",
        "Hwy 36",
        "Hwy 75",
        "I-30",
        "Hwy 18",
        "I-65",
        "Hwy 87",
        "I-35E",
        "Hwy 67",
        "I-35W",
        "I-29",
        "HWY 83",
        "Hwy 385",
        "I-69",
        "I-77",
        "I-94",
        "I-10",
        "Hwy 412",
        "Hwy 45A",
        "Hwy 287",
        "Hwy 288",
        "Hwy 287/50",
        "Hwy 99",
        "I-57",
        "Hwy 54",
        "I-78",
        "I-20",
        "I-25",
        "Hwy 74",
        "I-15",
        "Hwy 24",
        "I-49",
        "Hwy 50",
        "I-74",
        "Hwy 281",
        "Hwy 190",
        "I-8",
        "Hwy 63",
        "I-76",
        "I-37",
        "Hwy 2",
        "Hwy 69",
        "Hwy 275",
        "I-4",
        "Hwy 49",
        "I-24",
        "I-70",
        "Hwy 23",
        "I-135",
        "HWY 231",
        "Hwy 61",
        "",
        "Hwy 60",
        "Hwy 283",
        "I-71",
        "Hwy 169",
        "I-5",
        "I-82",
        "I-43",
        "Hwy 77",
        "Hwy 58",
        "I-155",
        "HWY 287",
        "I-45",
        "Hwy 81",
        "I-85",
        "HWY 50",
        "I-26",
        "I-39",
        "Hwy 41",
        "Hwy 370",
        "I-80",
        "Hwy 70",
        "I-16",
        "Loop 610",
        "Hwy 50/93",
        "I-95",
        "Hwy 6",
        "Hwy 59",
        "I-40",
        "Hwy 301",
        "I-280",
        "I-64",
        "Hwy 400",
        "Hwy 271",
        "Hwy 59/69/Loop 287",
        "Hwy 27",
        "Hwy 35",
        "I-295",
        "I-90",
        "I-55",
        "I-35",
        "I-72",
        "I-240",
        "I-75",
        "Hwy 72A",
        "I-41",
        "I-68",
        "Hwy 30",
        "I-84",
        "Hwy 225",
        "I-81",
      ],
      types: ["type1", "type2", "type3"],
      amenities: ["atm", "wifi"],
      restaraunts: ["Arby's", "Wendy's"],
      selectedType: [],
    };
  },
};
</script>
